export const themes = {
  dark: {
    foreground: '#FFFFFF',
    background: '#222222',
    url: 'blue',
    border: '#2E6390',
    headerBackground: '#37474F',
    headerForeground: '#FFFFFF',
    searchBarForeGround: 'dodgerblue',
    searchBarPlaceHolder: 'rgba(30,144,255,0.4)',
    searchBarBorder: '#2E6390',
    subTitleLng: '#434343',
    titleNotActive: '#AAAAAA',
  },
  light: {
    foreground: 'black',
    background: '#E5E5E5',
    url: 'blue',
    border: 'gray',
    headerBackground: 'white',
    headerForeground: 'dodgerblue',
    searchBarForeGround: 'dodgerblue',
    searchBarPlaceHolder: 'rgba(30,144,255,0.4)',
    searchBarBorder: 'dodgerblue',
    subTitleLng: '#AAAAAA',
    titleNotActive: '#434343',
  },
};
